// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: elecrow


#include "ui.h"
#include "ui_events.h"
#include "esp_log.h"


///////////////////// VARIABLES ////////////////////



// SCREEN: ui_Screen_2_Move
void ui_Screen_2_Move_screen_init(void);
lv_obj_t * ui_Screen_2_Move;
lv_obj_t * ui_Background1;
lv_obj_t * ui_S1_Content_Panel1;
lv_obj_t * ui_BTN_Move_XY;
lv_obj_t * ui_BTN_Move_XY_Top;
void ui_event_Arrow_Up_2(lv_event_t * e);
lv_obj_t * ui_Arrow_Up_2;
void ui_event_Arrow_Down_2(lv_event_t * e);
lv_obj_t * ui_Arrow_Down_2;
void ui_event_Arrow_Left_2(lv_event_t * e);
lv_obj_t * ui_Arrow_Left_2;
void ui_event_Arrow_Right_2(lv_event_t * e);
lv_obj_t * ui_Arrow_Right_2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



void ui_event_Arrow_Up_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        up_click(e);
    }
}

void ui_event_Arrow_Down_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        down_click(e);
    }
}

void ui_event_Arrow_Left_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
         left_click(e);
    }
}

void ui_event_Arrow_Right_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        right_click(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_2_Move_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_2_Move);
}
