// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: elecrow

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_2_Move
void ui_Screen_2_Move_screen_init(void);
lv_obj_t *ui_Screen_2_Move;
lv_obj_t *ui_Background1;
lv_obj_t *ui_S1_Content_Panel1;
lv_obj_t *ui_BTN_Move_XY;
lv_obj_t *ui_BTN_Move_XY_Top;
lv_obj_t *ui_Arrow_Up_2;
lv_obj_t *ui_Arrow_Down_2;
lv_obj_t *ui_Arrow_Left_2;
lv_obj_t *ui_Arrow_Right_2;
lv_obj_t *ui_Image1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_s[9] = {&ui_img_s1_png, &ui_img_s2_png, &ui_img_s3_png, &ui_img_s4_png, &ui_img_s5_png, &ui_img_s6_png, &ui_img_s7_png, &ui_img_s8_png, &ui_img_s9_png};
const lv_img_dsc_t *ui_imgset_se[9] = {&ui_img_se1_png, &ui_img_se2_png, &ui_img_se3_png, &ui_img_se4_png, &ui_img_se5_png, &ui_img_se6_png, &ui_img_se7_png, &ui_img_se8_png, &ui_img_se9_png};
const lv_img_dsc_t *ui_imgset_e[10] = {&ui_img_e1_png, &ui_img_e2_png, &ui_img_e3_png, &ui_img_e4_png, &ui_img_e5_png, &ui_img_e6_png, &ui_img_e7_png, &ui_img_e8_png, &ui_img_e9_png, &ui_img_e10_png};
const lv_img_dsc_t *ui_imgset_ne[7] = {&ui_img_ne1_png, &ui_img_ne2_png, &ui_img_ne3_png, &ui_img_ne4_png, &ui_img_ne5_png, &ui_img_ne6_png, &ui_img_ne7_png};
const lv_img_dsc_t *ui_imgset_n[4] = {&ui_img_n1_png, &ui_img_n2_png, &ui_img_n3_png, &ui_img_n4_png};
const lv_img_dsc_t *ui_imgset_nw[4] = {&ui_img_nw1_png, &ui_img_nw2_png, &ui_img_nw3_png, &ui_img_nw4_png};
const lv_img_dsc_t *ui_imgset_sw[10] = {&ui_img_sw0_png, &ui_img_sw1_png, &ui_img_sw2_png, &ui_img_sw3_png, &ui_img_sw4_png, &ui_img_sw5_png, &ui_img_sw6_png, &ui_img_sw7_png, &ui_img_sw8_png, &ui_img_sw9_png};
const lv_img_dsc_t *ui_imgset_w[10] = {&ui_img_w0_png, &ui_img_w1_png, &ui_img_w2_png, &ui_img_w3_png, &ui_img_w4_png, &ui_img_w5_png, &ui_img_w6_png, &ui_img_w7_png, &ui_img_w8_png, &ui_img_w9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen_2_Move_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen_2_Move);
}
