// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_CurrentsMonitorScreen
void ui_CurrentsMonitorScreen_screen_init(void);
lv_obj_t *ui_CurrentsMonitorScreen;
lv_obj_t *ui_RollerPanelCurrents;
lv_obj_t *ui_IndoorCurrent;
lv_obj_t *ui_IndoorCurrentLabel;
lv_obj_t *ui_IndoorCurrentValue;
lv_obj_t *ui_IndoorCurrentIcon;
lv_obj_t *ui_OutdoorCurrent;
lv_obj_t *ui_OutdoorCurrentLabel;
lv_obj_t *ui_OutdoorCurrentValue;
lv_obj_t *ui_OutdoorCurrentIcon;
lv_obj_t *ui_HidroforCurrent;
lv_obj_t *ui_HidroforCurrentLabel;
lv_obj_t *ui_HidroforCurrentValue;
lv_obj_t *ui_HidroforCurrentIcon;
void ui_event_FridgeCurrent( lv_event_t * e);
lv_obj_t *ui_FridgeCurrent;
lv_obj_t *ui_FridgeCurrentLabel;
lv_obj_t *ui_FridgeCurrentValue;
lv_obj_t *ui_FridgeCurrentIcon;
void ui_event_BatteryMonitor( lv_event_t * e);
lv_obj_t *ui_BatteryMonitor;
lv_obj_t *ui_BatteryMonitorLabel;
lv_obj_t *ui_BatteryMonitorVoltage;
lv_obj_t *ui_BatteryMonitorCurrent;
lv_obj_t *ui_BatteryMonitorIcon;
lv_obj_t *ui_HeadContainer5;
lv_obj_t *ui_OctoopiLogoImage5;
lv_obj_t *ui_SetupImage5;
lv_obj_t *ui_InMonitorContainer5;
lv_obj_t *ui_MonTrunkImage5;
lv_obj_t *ui_MonDoorImage5;
lv_obj_t *ui_MonPlugImage5;
lv_obj_t *ui_MonLampImage5;
lv_obj_t *ui_MonBlueImage5;
lv_obj_t *ui_MonWifiImage5;


// SCREEN: ui_LampControlScreen
void ui_LampControlScreen_screen_init(void);
lv_obj_t *ui_LampControlScreen;
lv_obj_t *ui_IndoorLampOnOffImage;
lv_obj_t *ui_IndoorLampOnOffIcon;
lv_obj_t *ui_OutdoorLampOnOffImage;
lv_obj_t *ui_OutdoorLampOnOffIcon;
lv_obj_t *ui_DimmerLampPanel;
lv_obj_t *ui_Slider2;
lv_obj_t *ui_DimmerLampPercentLabel;
lv_obj_t *ui_DimmerLampIcon;
lv_obj_t *ui_HeadContainer1;
lv_obj_t *ui_OctoopiLogoImage1;
lv_obj_t *ui_SetupImage1;
lv_obj_t *ui_InMonitorContainer1;
lv_obj_t *ui_MonTrunkImage1;
lv_obj_t *ui_MonDoorImage1;
lv_obj_t *ui_MonPlugImage1;
lv_obj_t *ui_MonLampImage1;
lv_obj_t *ui_MonBlueImage1;
lv_obj_t *ui_MonWifiImage1;


// SCREEN: ui_FridgeHidroControlScreen
void ui_FridgeHidroControlScreen_screen_init(void);
lv_obj_t *ui_FridgeHidroControlScreen;
lv_obj_t *ui_FridgeOnOffImage;
lv_obj_t *ui_FridgeOnOffIcon;
lv_obj_t *ui_HidroforOnOffImage;
lv_obj_t *ui_HidroforOnOffIcon;
lv_obj_t *ui_HeadContainer2;
lv_obj_t *ui_OctoopiLogoImage2;
lv_obj_t *ui_SetupImage2;
lv_obj_t *ui_InMonitorContainer2;
lv_obj_t *ui_MonTrunkImage2;
lv_obj_t *ui_MonDoorImage2;
lv_obj_t *ui_MonPlugImage2;
lv_obj_t *ui_MonLampImage2;
lv_obj_t *ui_MonBlueImage2;
lv_obj_t *ui_MonWifiImage2;


// SCREEN: ui_FuseMonitorScreen
void ui_FuseMonitorScreen_screen_init(void);
lv_obj_t *ui_FuseMonitorScreen;
lv_obj_t *ui_FuseMonRow1;
lv_obj_t *ui_FuseMon1;
lv_obj_t *ui_FuseMonImage1;
lv_obj_t *ui_FuseMonLabel1;
lv_obj_t *ui_FuseMon2;
lv_obj_t *ui_FuseMonImage2;
lv_obj_t *ui_FuseMonLabel2;
lv_obj_t *ui_FuseMon3;
lv_obj_t *ui_FuseMonImage3;
lv_obj_t *ui_FuseMonLabel3;
lv_obj_t *ui_FuseMon4;
lv_obj_t *ui_FuseMonImage4;
lv_obj_t *ui_FuseMonLabel4;
lv_obj_t *ui_FuseMon5;
lv_obj_t *ui_FuseMonImage5;
lv_obj_t *ui_FuseMonLabel5;
lv_obj_t *ui_FuseMonRow2;
lv_obj_t *ui_FuseMon6;
lv_obj_t *ui_FuseMonImage6;
lv_obj_t *ui_FuseMonLabel6;
lv_obj_t *ui_FuseMon7;
lv_obj_t *ui_FuseMonImage7;
lv_obj_t *ui_FuseMonLabel7;
lv_obj_t *ui_FuseMon8;
lv_obj_t *ui_FuseMonImage8;
lv_obj_t *ui_FuseMonLabel8;
lv_obj_t *ui_FuseMon9;
lv_obj_t *ui_FuseMonImage9;
lv_obj_t *ui_FuseMonLabel9;
lv_obj_t *ui_FuseMon10;
lv_obj_t *ui_FuseMonImage10;
lv_obj_t *ui_FuseMonLabel10;
lv_obj_t *ui_HeadContainer3;
lv_obj_t *ui_OctoopiLogoImage3;
lv_obj_t *ui_SetupImage3;
lv_obj_t *ui_InMonitorContainer3;
lv_obj_t *ui_MonTrunkImage3;
lv_obj_t *ui_MonDoorImage3;
lv_obj_t *ui_MonPlugImage3;
lv_obj_t *ui_MonLampImage3;
lv_obj_t *ui_MonBlueImage3;
lv_obj_t *ui_MonWifiImage3;


// SCREEN: ui_RGBLampScreen
void ui_RGBLampScreen_screen_init(void);
lv_obj_t *ui_RGBLampScreen;
lv_obj_t *ui_RGBSetContainer;
lv_obj_t *ui_RGBSetColorwheel;
lv_obj_t *ui_RGBSetSwitch;
lv_obj_t *ui_RGBFunctionContainer;
lv_obj_t *ui_RGBSetF1Button;
lv_obj_t *ui_RGBSetF1Label;
lv_obj_t *ui_RGBSetF2Button;
lv_obj_t *ui_RGBSetF2Label;
lv_obj_t *ui_RGBSetF3Button;
lv_obj_t *ui_RGBSetF3Label;
lv_obj_t *ui_RGBSetF4Button;
lv_obj_t *ui_RGBSetF4Label;
lv_obj_t *ui_RGBSetF5Button;
lv_obj_t *ui_RGBSetF5Label;
lv_obj_t *ui_RGBSetF6Button;
lv_obj_t *ui_RGBSetF6Label;
lv_obj_t *ui_HeadContainer4;
lv_obj_t *ui_OctoopiLogoImage4;
lv_obj_t *ui_SetupImage4;
lv_obj_t *ui_InMonitorContainer4;
lv_obj_t *ui_MonTrunkImage4;
lv_obj_t *ui_MonDoorImage4;
lv_obj_t *ui_MonPlugImage4;
lv_obj_t *ui_MonLampImage4;
lv_obj_t *ui_MonBlueImage4;
lv_obj_t *ui_MonWifiImage4;


// SCREEN: ui_PopupScreen
void ui_PopupScreen_screen_init(void);
lv_obj_t *ui_PopupScreen;
lv_obj_t *ui_HeadContainer6;
lv_obj_t *ui_OctoopiLogoImage6;
lv_obj_t *ui_SetupImage6;
lv_obj_t *ui_InMonitorContainer6;
lv_obj_t *ui_MonTrunkImage6;
lv_obj_t *ui_MonDoorImage6;
lv_obj_t *ui_MonPlugImage6;
lv_obj_t *ui_MonLampImage6;
lv_obj_t *ui_MonBlueImage6;
lv_obj_t *ui_MonWifiImage6;
lv_obj_t *ui_PopupContainer;
lv_obj_t *ui_PopupImage;
lv_obj_t *ui_PopupLabel;
lv_obj_t *ui_PopupButton;
lv_obj_t *ui_PopupButtonLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1601711520[3] = {&ui_img_86249921, &ui_img_1521626150, &ui_img_439896971};
const lv_img_dsc_t *ui_imgset_temp[2] = {&ui_img_temp1_png, &ui_img_temp2_png};
const lv_img_dsc_t *ui_imgset_water_drain_[10] = {&ui_img_water_drain_10_png, &ui_img_water_drain_100_png, &ui_img_water_drain_20_png, &ui_img_water_drain_30_png, &ui_img_water_drain_40_png, &ui_img_water_drain_50_png, &ui_img_water_drain_60_png, &ui_img_water_drain_70_png, &ui_img_water_drain_80_png, &ui_img_water_drain_90_png};
const lv_img_dsc_t *ui_imgset_water_fresh_[11] = {&ui_img_water_fresh_00_png, &ui_img_water_fresh_10_png, &ui_img_water_fresh_100_png, &ui_img_water_fresh_20_png, &ui_img_water_fresh_30_png, &ui_img_water_fresh_40_png, &ui_img_water_fresh_50_png, &ui_img_water_fresh_60_png, &ui_img_water_fresh_70_png, &ui_img_water_fresh_80_png, &ui_img_water_fresh_90_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_FridgeCurrent( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      FridgeClick( e );
}
}
void ui_event_BatteryMonitor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_BatteryMonitor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_CurrentsMonitorScreen_screen_init();
ui_LampControlScreen_screen_init();
ui_FridgeHidroControlScreen_screen_init();
ui_FuseMonitorScreen_screen_init();
ui_RGBLampScreen_screen_init();
ui_PopupScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_CurrentsMonitorScreen);
}
