// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#ifndef _MINICOMBINE2_UI_H
#define _MINICOMBINE2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

    #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_CurrentsMonitorScreen
void ui_CurrentsMonitorScreen_screen_init(void);
extern lv_obj_t *ui_CurrentsMonitorScreen;
extern lv_obj_t *ui_RollerPanelCurrents;
extern lv_obj_t *ui_IndoorCurrent;
extern lv_obj_t *ui_IndoorCurrentLabel;
extern lv_obj_t *ui_IndoorCurrentValue;
extern lv_obj_t *ui_IndoorCurrentIcon;
extern lv_obj_t *ui_OutdoorCurrent;
extern lv_obj_t *ui_OutdoorCurrentLabel;
extern lv_obj_t *ui_OutdoorCurrentValue;
extern lv_obj_t *ui_OutdoorCurrentIcon;
extern lv_obj_t *ui_HidroforCurrent;
extern lv_obj_t *ui_HidroforCurrentLabel;
extern lv_obj_t *ui_HidroforCurrentValue;
extern lv_obj_t *ui_HidroforCurrentIcon;
void ui_event_FridgeCurrent( lv_event_t * e);
extern lv_obj_t *ui_FridgeCurrent;
extern lv_obj_t *ui_FridgeCurrentLabel;
extern lv_obj_t *ui_FridgeCurrentValue;
extern lv_obj_t *ui_FridgeCurrentIcon;
void ui_event_BatteryMonitor( lv_event_t * e);
extern lv_obj_t *ui_BatteryMonitor;
extern lv_obj_t *ui_BatteryMonitorLabel;
extern lv_obj_t *ui_BatteryMonitorVoltage;
extern lv_obj_t *ui_BatteryMonitorCurrent;
extern lv_obj_t *ui_BatteryMonitorIcon;
extern lv_obj_t *ui_HeadContainer5;
extern lv_obj_t *ui_OctoopiLogoImage5;
extern lv_obj_t *ui_SetupImage5;
extern lv_obj_t *ui_InMonitorContainer5;
extern lv_obj_t *ui_MonTrunkImage5;
extern lv_obj_t *ui_MonDoorImage5;
extern lv_obj_t *ui_MonPlugImage5;
extern lv_obj_t *ui_MonLampImage5;
extern lv_obj_t *ui_MonBlueImage5;
extern lv_obj_t *ui_MonWifiImage5;
// SCREEN: ui_LampControlScreen
void ui_LampControlScreen_screen_init(void);
extern lv_obj_t *ui_LampControlScreen;
extern lv_obj_t *ui_IndoorLampOnOffImage;
extern lv_obj_t *ui_IndoorLampOnOffIcon;
extern lv_obj_t *ui_OutdoorLampOnOffImage;
extern lv_obj_t *ui_OutdoorLampOnOffIcon;
extern lv_obj_t *ui_DimmerLampPanel;
extern lv_obj_t *ui_Slider2;
extern lv_obj_t *ui_DimmerLampPercentLabel;
extern lv_obj_t *ui_DimmerLampIcon;
extern lv_obj_t *ui_HeadContainer1;
extern lv_obj_t *ui_OctoopiLogoImage1;
extern lv_obj_t *ui_SetupImage1;
extern lv_obj_t *ui_InMonitorContainer1;
extern lv_obj_t *ui_MonTrunkImage1;
extern lv_obj_t *ui_MonDoorImage1;
extern lv_obj_t *ui_MonPlugImage1;
extern lv_obj_t *ui_MonLampImage1;
extern lv_obj_t *ui_MonBlueImage1;
extern lv_obj_t *ui_MonWifiImage1;
// SCREEN: ui_FridgeHidroControlScreen
void ui_FridgeHidroControlScreen_screen_init(void);
extern lv_obj_t *ui_FridgeHidroControlScreen;
extern lv_obj_t *ui_FridgeOnOffImage;
extern lv_obj_t *ui_FridgeOnOffIcon;
extern lv_obj_t *ui_HidroforOnOffImage;
extern lv_obj_t *ui_HidroforOnOffIcon;
extern lv_obj_t *ui_HeadContainer2;
extern lv_obj_t *ui_OctoopiLogoImage2;
extern lv_obj_t *ui_SetupImage2;
extern lv_obj_t *ui_InMonitorContainer2;
extern lv_obj_t *ui_MonTrunkImage2;
extern lv_obj_t *ui_MonDoorImage2;
extern lv_obj_t *ui_MonPlugImage2;
extern lv_obj_t *ui_MonLampImage2;
extern lv_obj_t *ui_MonBlueImage2;
extern lv_obj_t *ui_MonWifiImage2;
// SCREEN: ui_FuseMonitorScreen
void ui_FuseMonitorScreen_screen_init(void);
extern lv_obj_t *ui_FuseMonitorScreen;
extern lv_obj_t *ui_FuseMonRow1;
extern lv_obj_t *ui_FuseMon1;
extern lv_obj_t *ui_FuseMonImage1;
extern lv_obj_t *ui_FuseMonLabel1;
extern lv_obj_t *ui_FuseMon2;
extern lv_obj_t *ui_FuseMonImage2;
extern lv_obj_t *ui_FuseMonLabel2;
extern lv_obj_t *ui_FuseMon3;
extern lv_obj_t *ui_FuseMonImage3;
extern lv_obj_t *ui_FuseMonLabel3;
extern lv_obj_t *ui_FuseMon4;
extern lv_obj_t *ui_FuseMonImage4;
extern lv_obj_t *ui_FuseMonLabel4;
extern lv_obj_t *ui_FuseMon5;
extern lv_obj_t *ui_FuseMonImage5;
extern lv_obj_t *ui_FuseMonLabel5;
extern lv_obj_t *ui_FuseMonRow2;
extern lv_obj_t *ui_FuseMon6;
extern lv_obj_t *ui_FuseMonImage6;
extern lv_obj_t *ui_FuseMonLabel6;
extern lv_obj_t *ui_FuseMon7;
extern lv_obj_t *ui_FuseMonImage7;
extern lv_obj_t *ui_FuseMonLabel7;
extern lv_obj_t *ui_FuseMon8;
extern lv_obj_t *ui_FuseMonImage8;
extern lv_obj_t *ui_FuseMonLabel8;
extern lv_obj_t *ui_FuseMon9;
extern lv_obj_t *ui_FuseMonImage9;
extern lv_obj_t *ui_FuseMonLabel9;
extern lv_obj_t *ui_FuseMon10;
extern lv_obj_t *ui_FuseMonImage10;
extern lv_obj_t *ui_FuseMonLabel10;
extern lv_obj_t *ui_HeadContainer3;
extern lv_obj_t *ui_OctoopiLogoImage3;
extern lv_obj_t *ui_SetupImage3;
extern lv_obj_t *ui_InMonitorContainer3;
extern lv_obj_t *ui_MonTrunkImage3;
extern lv_obj_t *ui_MonDoorImage3;
extern lv_obj_t *ui_MonPlugImage3;
extern lv_obj_t *ui_MonLampImage3;
extern lv_obj_t *ui_MonBlueImage3;
extern lv_obj_t *ui_MonWifiImage3;
// SCREEN: ui_RGBLampScreen
void ui_RGBLampScreen_screen_init(void);
extern lv_obj_t *ui_RGBLampScreen;
extern lv_obj_t *ui_RGBSetContainer;
extern lv_obj_t *ui_RGBSetColorwheel;
extern lv_obj_t *ui_RGBSetSwitch;
extern lv_obj_t *ui_RGBFunctionContainer;
extern lv_obj_t *ui_RGBSetF1Button;
extern lv_obj_t *ui_RGBSetF1Label;
extern lv_obj_t *ui_RGBSetF2Button;
extern lv_obj_t *ui_RGBSetF2Label;
extern lv_obj_t *ui_RGBSetF3Button;
extern lv_obj_t *ui_RGBSetF3Label;
extern lv_obj_t *ui_RGBSetF4Button;
extern lv_obj_t *ui_RGBSetF4Label;
extern lv_obj_t *ui_RGBSetF5Button;
extern lv_obj_t *ui_RGBSetF5Label;
extern lv_obj_t *ui_RGBSetF6Button;
extern lv_obj_t *ui_RGBSetF6Label;
extern lv_obj_t *ui_HeadContainer4;
extern lv_obj_t *ui_OctoopiLogoImage4;
extern lv_obj_t *ui_SetupImage4;
extern lv_obj_t *ui_InMonitorContainer4;
extern lv_obj_t *ui_MonTrunkImage4;
extern lv_obj_t *ui_MonDoorImage4;
extern lv_obj_t *ui_MonPlugImage4;
extern lv_obj_t *ui_MonLampImage4;
extern lv_obj_t *ui_MonBlueImage4;
extern lv_obj_t *ui_MonWifiImage4;
// SCREEN: ui_PopupScreen
void ui_PopupScreen_screen_init(void);
extern lv_obj_t *ui_PopupScreen;
extern lv_obj_t *ui_HeadContainer6;
extern lv_obj_t *ui_OctoopiLogoImage6;
extern lv_obj_t *ui_SetupImage6;
extern lv_obj_t *ui_InMonitorContainer6;
extern lv_obj_t *ui_MonTrunkImage6;
extern lv_obj_t *ui_MonDoorImage6;
extern lv_obj_t *ui_MonPlugImage6;
extern lv_obj_t *ui_MonLampImage6;
extern lv_obj_t *ui_MonBlueImage6;
extern lv_obj_t *ui_MonWifiImage6;
extern lv_obj_t *ui_PopupContainer;
extern lv_obj_t *ui_PopupImage;
extern lv_obj_t *ui_PopupLabel;
extern lv_obj_t *ui_PopupButton;
extern lv_obj_t *ui_PopupButtonLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_indoor_lamp_48_w_png);   // assets\indoor_lamp_48_w.png
LV_IMG_DECLARE( ui_img_outdoor_lamp_48_w_png);   // assets\outdoor_lamp_48_w.png
LV_IMG_DECLARE( ui_img_hidrofor_48_w_png);   // assets\hidrofor_48_w.png
LV_IMG_DECLARE( ui_img_fridge_48_w_png);   // assets\fridge_48_w.png
LV_IMG_DECLARE( ui_img_battery_84_w_png);   // assets\battery_84_w.png
LV_IMG_DECLARE( ui_img_octoopilogo_png);   // assets\OctoopiLogo.png
LV_IMG_DECLARE( ui_img_setup_png);   // assets\setup.png
LV_IMG_DECLARE( ui_img_trunk_open_png);   // assets\trunk_open.png
LV_IMG_DECLARE( ui_img_door_lock_close_png);   // assets\door_lock_close.png
LV_IMG_DECLARE( ui_img_plug_yes_png);   // assets\plug_yes.png
LV_IMG_DECLARE( ui_img_outdoor_lamp_on_png);   // assets\outdoor_lamp_on.png
LV_IMG_DECLARE( ui_img_bluetooth_yes_png);   // assets\bluetooth_yes.png
LV_IMG_DECLARE( ui_img_wifi_yes_png);   // assets\wifi_yes.png
LV_IMG_DECLARE( ui_img_1521626150);   // assets\Button+Card-2.png
LV_IMG_DECLARE( ui_img_input_card_png);   // assets\input_card.png
LV_IMG_DECLARE( ui_img_indoor_lamp_48_g_png);   // assets\indoor_lamp_48_g.png
LV_IMG_DECLARE( ui_img_439896971);   // assets\Button+Card-3.png
LV_IMG_DECLARE( ui_img_fuse_w_png);   // assets\Fuse_W.png
LV_IMG_DECLARE( ui_img_batterycharging_png);   // assets\batterycharging.png
LV_IMG_DECLARE( ui_img_blocksettings_png);   // assets\BlockSettings.png
LV_IMG_DECLARE( ui_img_86249921);   // assets\Button+Card-1.png
LV_IMG_DECLARE( ui_img_1590672063);   // assets\Button+Card.png
LV_IMG_DECLARE( ui_img_button_png);   // assets\Button.png
LV_IMG_DECLARE( ui_img_button_card_b_png);   // assets\Button_Card_B.png
LV_IMG_DECLARE( ui_img_button_card_bl_png);   // assets\Button_Card_BL.png
LV_IMG_DECLARE( ui_img_button_card_g_png);   // assets\Button_Card_G.png
LV_IMG_DECLARE( ui_img_button_card_gr_png);   // assets\Button_Card_GR.png
LV_IMG_DECLARE( ui_img_button_card_r_png);   // assets\Button_Card_R.png
LV_IMG_DECLARE( ui_img_celsius_in_png);   // assets\celsius_in.png
LV_IMG_DECLARE( ui_img_celsius_out_png);   // assets\celsius_out.png
LV_IMG_DECLARE( ui_img_flag_germany_png);   // assets\flag_germany.png
LV_IMG_DECLARE( ui_img_flag_turkey_png);   // assets\flag_turkey.png
LV_IMG_DECLARE( ui_img_flag_unitedkingdom_png);   // assets\flag_unitedkingdom.png
LV_IMG_DECLARE( ui_img_fridge_48_g_png);   // assets\fridge_48_g.png
LV_IMG_DECLARE( ui_img_fridge_48_gr_png);   // assets\fridge_48_gr.png
LV_IMG_DECLARE( ui_img_fridge_48_r_png);   // assets\fridge_48_r.png
LV_IMG_DECLARE( ui_img_fuse_b_png);   // assets\Fuse_B.png
LV_IMG_DECLARE( ui_img_fuse_r_png);   // assets\Fuse_R.png
LV_IMG_DECLARE( ui_img_hidrofor_48_g_png);   // assets\hidrofor_48_g.png
LV_IMG_DECLARE( ui_img_hidrofor_48_gr_png);   // assets\hidrofor_48_gr.png
LV_IMG_DECLARE( ui_img_hidrofor_48_r_png);   // assets\hidrofor_48_r.png
LV_IMG_DECLARE( ui_img_indoor_lamp_48_gr_png);   // assets\indoor_lamp_48_gr.png
LV_IMG_DECLARE( ui_img_indoor_lamp_48_r_png);   // assets\indoor_lamp_48_r.png
LV_IMG_DECLARE( ui_img_leftgo_png);   // assets\LeftGo.png
LV_IMG_DECLARE( ui_img_mertechlogo_png);   // assets\MertechLogo.png
LV_IMG_DECLARE( ui_img_octoopibanner_png);   // assets\OctoopiBanner.png
LV_IMG_DECLARE( ui_img_outdoor_lamp_48_g_png);   // assets\outdoor_lamp_48_g.png
LV_IMG_DECLARE( ui_img_outdoor_lamp_48_gr_png);   // assets\outdoor_lamp_48_gr.png
LV_IMG_DECLARE( ui_img_outdoor_lamp_48_r_png);   // assets\outdoor_lamp_48_r.png
LV_IMG_DECLARE( ui_img_ph_moon_fill_png);   // assets\ph_moon_fill.png
LV_IMG_DECLARE( ui_img_rightgo_png);   // assets\RightGo.png
LV_IMG_DECLARE( ui_img_setup_icon_png);   // assets\setup_icon.png
LV_IMG_DECLARE( ui_img_temp1_png);   // assets\temp1.png
LV_IMG_DECLARE( ui_img_temp2_png);   // assets\temp2.png
LV_IMG_DECLARE( ui_img_track_light_flip_png);   // assets\track_light_flip.png
LV_IMG_DECLARE( ui_img_tv_monitor_png);   // assets\tv_monitor.png
LV_IMG_DECLARE( ui_img_water_drain_10_png);   // assets\water_drain_10.png
LV_IMG_DECLARE( ui_img_water_drain_100_png);   // assets\water_drain_100.png
LV_IMG_DECLARE( ui_img_water_drain_100_i_png);   // assets\water_drain_100_i.png
LV_IMG_DECLARE( ui_img_water_drain_20_png);   // assets\water_drain_20.png
LV_IMG_DECLARE( ui_img_water_drain_30_png);   // assets\water_drain_30.png
LV_IMG_DECLARE( ui_img_water_drain_40_png);   // assets\water_drain_40.png
LV_IMG_DECLARE( ui_img_water_drain_50_png);   // assets\water_drain_50.png
LV_IMG_DECLARE( ui_img_water_drain_60_png);   // assets\water_drain_60.png
LV_IMG_DECLARE( ui_img_water_drain_70_png);   // assets\water_drain_70.png
LV_IMG_DECLARE( ui_img_water_drain_80_png);   // assets\water_drain_80.png
LV_IMG_DECLARE( ui_img_water_drain_90_png);   // assets\water_drain_90.png
LV_IMG_DECLARE( ui_img_water_drain_q_png);   // assets\water_drain_q.png
LV_IMG_DECLARE( ui_img_water_fresh_00_png);   // assets\water_fresh_00.png
LV_IMG_DECLARE( ui_img_water_fresh_00_i_png);   // assets\water_fresh_00_i.png
LV_IMG_DECLARE( ui_img_water_fresh_10_png);   // assets\water_fresh_10.png
LV_IMG_DECLARE( ui_img_water_fresh_100_png);   // assets\water_fresh_100.png
LV_IMG_DECLARE( ui_img_water_fresh_20_png);   // assets\water_fresh_20.png
LV_IMG_DECLARE( ui_img_water_fresh_30_png);   // assets\water_fresh_30.png
LV_IMG_DECLARE( ui_img_water_fresh_40_png);   // assets\water_fresh_40.png
LV_IMG_DECLARE( ui_img_water_fresh_50_png);   // assets\water_fresh_50.png
LV_IMG_DECLARE( ui_img_water_fresh_60_png);   // assets\water_fresh_60.png
LV_IMG_DECLARE( ui_img_water_fresh_70_png);   // assets\water_fresh_70.png
LV_IMG_DECLARE( ui_img_water_fresh_80_png);   // assets\water_fresh_80.png
LV_IMG_DECLARE( ui_img_water_fresh_90_png);   // assets\water_fresh_90.png
LV_IMG_DECLARE( ui_img_water_fresh_q_png);   // assets\water_fresh_q.png

LV_FONT_DECLARE( ui_font_Leddisplay50);
LV_FONT_DECLARE( ui_font_Leddisplay16);
LV_FONT_DECLARE( ui_font_Leddisplay20);
LV_FONT_DECLARE( ui_font_Leddisplay30);
LV_FONT_DECLARE( ui_font_Leddisplay50);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
