// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: elecrow

#ifndef _ELECROW_UI_H
#define _ELECROW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen_2_Move
void ui_Screen_2_Move_screen_init(void);
extern lv_obj_t *ui_Screen_2_Move;
extern lv_obj_t *ui_Background1;
extern lv_obj_t *ui_S1_Content_Panel1;
extern lv_obj_t *ui_BTN_Move_XY;
extern lv_obj_t *ui_BTN_Move_XY_Top;
extern lv_obj_t *ui_Arrow_Up_2;
extern lv_obj_t *ui_Arrow_Down_2;
extern lv_obj_t *ui_Arrow_Left_2;
extern lv_obj_t *ui_Arrow_Right_2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_bg_png);   // assets\bg.png
LV_IMG_DECLARE( ui_img_btn_pad_bottom_png);   // assets\btn_pad_bottom.png
LV_IMG_DECLARE( ui_img_btn_pad_top_png);   // assets\btn_pad_top.png
LV_IMG_DECLARE( ui_img_arrow_up_png);   // assets\arrow_up.png
LV_IMG_DECLARE( ui_img_arrow_down_png);   // assets\arrow_down.png
LV_IMG_DECLARE( ui_img_arrow_left_png);   // assets\arrow_left.png
LV_IMG_DECLARE( ui_img_arrow_right_png);   // assets\arrow_right.png
LV_IMG_DECLARE( ui_img_e1_png);   // assets\e1.png
LV_IMG_DECLARE( ui_img_s1_png);   // assets\s1.png
LV_IMG_DECLARE( ui_img_s2_png);   // assets\s2.png
LV_IMG_DECLARE( ui_img_s3_png);   // assets\s3.png
LV_IMG_DECLARE( ui_img_s4_png);   // assets\s4.png
LV_IMG_DECLARE( ui_img_s5_png);   // assets\s5.png
LV_IMG_DECLARE( ui_img_s6_png);   // assets\s6.png
LV_IMG_DECLARE( ui_img_se1_png);   // assets\se1.png
LV_IMG_DECLARE( ui_img_se2_png);   // assets\se2.png
LV_IMG_DECLARE( ui_img_se3_png);   // assets\se3.png
LV_IMG_DECLARE( ui_img_se4_png);   // assets\se4.png
LV_IMG_DECLARE( ui_img_se5_png);   // assets\se5.png
LV_IMG_DECLARE( ui_img_se6_png);   // assets\se6.png
LV_IMG_DECLARE( ui_img_e2_png);   // assets\e2.png
LV_IMG_DECLARE( ui_img_e3_png);   // assets\e3.png
LV_IMG_DECLARE( ui_img_e4_png);   // assets\e4.png
LV_IMG_DECLARE( ui_img_e5_png);   // assets\e5.png
LV_IMG_DECLARE( ui_img_e6_png);   // assets\e6.png
LV_IMG_DECLARE( ui_img_e7_png);   // assets\e7.png
LV_IMG_DECLARE( ui_img_ne1_png);   // assets\ne1.png
LV_IMG_DECLARE( ui_img_ne2_png);   // assets\ne2.png
LV_IMG_DECLARE( ui_img_ne3_png);   // assets\ne3.png
LV_IMG_DECLARE( ui_img_ne4_png);   // assets\ne4.png
LV_IMG_DECLARE( ui_img_n1_png);   // assets\n1.png
LV_IMG_DECLARE( ui_img_n2_png);   // assets\n2.png
LV_IMG_DECLARE( ui_img_n3_png);   // assets\n3.png
LV_IMG_DECLARE( ui_img_n4_png);   // assets\n4.png
LV_IMG_DECLARE( ui_img_nw1_png);   // assets\nw1.png
LV_IMG_DECLARE( ui_img_nw2_png);   // assets\nw2.png
LV_IMG_DECLARE( ui_img_nw3_png);   // assets\nw3.png
LV_IMG_DECLARE( ui_img_sw1_png);   // assets\sw1.png
LV_IMG_DECLARE( ui_img_sw2_png);   // assets\sw2.png
LV_IMG_DECLARE( ui_img_sw3_png);   // assets\sw3.png
LV_IMG_DECLARE( ui_img_ne5_png);   // assets\ne5.png
LV_IMG_DECLARE( ui_img_w1_png);   // assets\w1.png
LV_IMG_DECLARE( ui_img_w2_png);   // assets\w2.png
LV_IMG_DECLARE( ui_img_w3_png);   // assets\w3.png
LV_IMG_DECLARE( ui_img_s7_png);   // assets\s7.png
LV_IMG_DECLARE( ui_img_s8_png);   // assets\s8.png
LV_IMG_DECLARE( ui_img_se7_png);   // assets\se7.png
LV_IMG_DECLARE( ui_img_se8_png);   // assets\se8.png
LV_IMG_DECLARE( ui_img_se9_png);   // assets\se9.png
LV_IMG_DECLARE( ui_img_e8_png);   // assets\e8.png
LV_IMG_DECLARE( ui_img_e9_png);   // assets\e9.png
LV_IMG_DECLARE( ui_img_e10_png);   // assets\e10.png
LV_IMG_DECLARE( ui_img_s9_png);   // assets\s9.png
LV_IMG_DECLARE( ui_img_sw4_png);   // assets\sw4.png
LV_IMG_DECLARE( ui_img_sw5_png);   // assets\sw5.png
LV_IMG_DECLARE( ui_img_sw6_png);   // assets\sw6.png
LV_IMG_DECLARE( ui_img_sw7_png);   // assets\sw7.png
LV_IMG_DECLARE( ui_img_sw8_png);   // assets\sw8.png
LV_IMG_DECLARE( ui_img_sw9_png);   // assets\sw9.png
LV_IMG_DECLARE( ui_img_ne6_png);   // assets\ne6.png
LV_IMG_DECLARE( ui_img_ne7_png);   // assets\ne7.png
LV_IMG_DECLARE( ui_img_w4_png);   // assets\w4.png
LV_IMG_DECLARE( ui_img_w5_png);   // assets\w5.png
LV_IMG_DECLARE( ui_img_w6_png);   // assets\w6.png
LV_IMG_DECLARE( ui_img_w7_png);   // assets\w7.png
LV_IMG_DECLARE( ui_img_sw0_png);   // assets\sw0.png
LV_IMG_DECLARE( ui_img_nw4_png);   // assets\nw4.png
LV_IMG_DECLARE( ui_img_w0_png);   // assets\w0.png
LV_IMG_DECLARE( ui_img_w8_png);   // assets\w8.png
LV_IMG_DECLARE( ui_img_w9_png);   // assets\w9.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
