// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"

void ui_CurrentsMonitorScreen_screen_init(void)
{
ui_CurrentsMonitorScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CurrentsMonitorScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CurrentsMonitorScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurrentsMonitorScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RollerPanelCurrents = lv_obj_create(ui_CurrentsMonitorScreen);
lv_obj_set_width( ui_RollerPanelCurrents, 323);
lv_obj_set_height( ui_RollerPanelCurrents, 216);
lv_obj_set_x( ui_RollerPanelCurrents, 2 );
lv_obj_set_y( ui_RollerPanelCurrents, 12 );
lv_obj_set_align( ui_RollerPanelCurrents, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RollerPanelCurrents, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RollerPanelCurrents, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerPanelCurrents, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RollerPanelCurrents, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RollerPanelCurrents, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_RollerPanelCurrents, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_RollerPanelCurrents, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_RollerPanelCurrents, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_RollerPanelCurrents, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_RollerPanelCurrents, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_RollerPanelCurrents, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IndoorCurrent = lv_obj_create(ui_RollerPanelCurrents);
lv_obj_set_width( ui_IndoorCurrent, 148);
lv_obj_set_height( ui_IndoorCurrent, 55);
lv_obj_set_x( ui_IndoorCurrent, 68 );
lv_obj_set_y( ui_IndoorCurrent, -65 );
lv_obj_set_align( ui_IndoorCurrent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_IndoorCurrent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_IndoorCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_IndoorCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IndoorCurrent, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IndoorCurrentLabel = lv_label_create(ui_IndoorCurrent);
lv_obj_set_width( ui_IndoorCurrentLabel, 90);
lv_obj_set_height( ui_IndoorCurrentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IndoorCurrentLabel, 24 );
lv_obj_set_y( ui_IndoorCurrentLabel, -12 );
lv_obj_set_align( ui_IndoorCurrentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_IndoorCurrentLabel,"Indoor");
lv_obj_set_style_text_font(ui_IndoorCurrentLabel, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IndoorCurrentValue = lv_label_create(ui_IndoorCurrent);
lv_obj_set_width( ui_IndoorCurrentValue, 90);
lv_obj_set_height( ui_IndoorCurrentValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IndoorCurrentValue, 24 );
lv_obj_set_y( ui_IndoorCurrentValue, 11 );
lv_obj_set_align( ui_IndoorCurrentValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_IndoorCurrentValue,"0.8 A");
lv_obj_set_style_text_font(ui_IndoorCurrentValue, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IndoorCurrentIcon = lv_img_create(ui_IndoorCurrent);
lv_img_set_src(ui_IndoorCurrentIcon, &ui_img_indoor_lamp_48_w_png);
lv_obj_set_width( ui_IndoorCurrentIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IndoorCurrentIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IndoorCurrentIcon, -47 );
lv_obj_set_y( ui_IndoorCurrentIcon, 0 );
lv_obj_set_align( ui_IndoorCurrentIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_IndoorCurrentIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IndoorCurrentIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_IndoorCurrentIcon,200);

ui_OutdoorCurrent = lv_obj_create(ui_RollerPanelCurrents);
lv_obj_set_width( ui_OutdoorCurrent, 148);
lv_obj_set_height( ui_OutdoorCurrent, 55);
lv_obj_set_x( ui_OutdoorCurrent, 68 );
lv_obj_set_y( ui_OutdoorCurrent, -11 );
lv_obj_set_align( ui_OutdoorCurrent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_OutdoorCurrent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OutdoorCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutdoorCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutdoorCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutdoorCurrentLabel = lv_label_create(ui_OutdoorCurrent);
lv_obj_set_width( ui_OutdoorCurrentLabel, 90);
lv_obj_set_height( ui_OutdoorCurrentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutdoorCurrentLabel, 24 );
lv_obj_set_y( ui_OutdoorCurrentLabel, -11 );
lv_obj_set_align( ui_OutdoorCurrentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutdoorCurrentLabel,"Outdoor");
lv_obj_set_style_text_font(ui_OutdoorCurrentLabel, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutdoorCurrentValue = lv_label_create(ui_OutdoorCurrent);
lv_obj_set_width( ui_OutdoorCurrentValue, 90);
lv_obj_set_height( ui_OutdoorCurrentValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutdoorCurrentValue, 24 );
lv_obj_set_y( ui_OutdoorCurrentValue, 11 );
lv_obj_set_align( ui_OutdoorCurrentValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_OutdoorCurrentValue,"0.5 A");
lv_obj_set_style_text_font(ui_OutdoorCurrentValue, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutdoorCurrentIcon = lv_img_create(ui_OutdoorCurrent);
lv_img_set_src(ui_OutdoorCurrentIcon, &ui_img_outdoor_lamp_48_w_png);
lv_obj_set_width( ui_OutdoorCurrentIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutdoorCurrentIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutdoorCurrentIcon, -47 );
lv_obj_set_y( ui_OutdoorCurrentIcon, 0 );
lv_obj_set_align( ui_OutdoorCurrentIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OutdoorCurrentIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OutdoorCurrentIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OutdoorCurrentIcon,200);

ui_HidroforCurrent = lv_obj_create(ui_RollerPanelCurrents);
lv_obj_set_width( ui_HidroforCurrent, 148);
lv_obj_set_height( ui_HidroforCurrent, 55);
lv_obj_set_x( ui_HidroforCurrent, -80 );
lv_obj_set_y( ui_HidroforCurrent, -65 );
lv_obj_set_align( ui_HidroforCurrent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HidroforCurrent, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_HidroforCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HidroforCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HidroforCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HidroforCurrentLabel = lv_label_create(ui_HidroforCurrent);
lv_obj_set_width( ui_HidroforCurrentLabel, 90);
lv_obj_set_height( ui_HidroforCurrentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HidroforCurrentLabel, 24 );
lv_obj_set_y( ui_HidroforCurrentLabel, -8 );
lv_obj_set_align( ui_HidroforCurrentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HidroforCurrentLabel,"Hidrofor");
lv_obj_clear_flag( ui_HidroforCurrentLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_HidroforCurrentLabel, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HidroforCurrentValue = lv_label_create(ui_HidroforCurrent);
lv_obj_set_width( ui_HidroforCurrentValue, 90);
lv_obj_set_height( ui_HidroforCurrentValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HidroforCurrentValue, 24 );
lv_obj_set_y( ui_HidroforCurrentValue, 12 );
lv_obj_set_align( ui_HidroforCurrentValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_HidroforCurrentValue,"10.8 A");
lv_obj_clear_flag( ui_HidroforCurrentValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_HidroforCurrentValue, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HidroforCurrentIcon = lv_img_create(ui_HidroforCurrent);
lv_img_set_src(ui_HidroforCurrentIcon, &ui_img_hidrofor_48_w_png);
lv_obj_set_width( ui_HidroforCurrentIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HidroforCurrentIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HidroforCurrentIcon, -47 );
lv_obj_set_y( ui_HidroforCurrentIcon, 0 );
lv_obj_set_align( ui_HidroforCurrentIcon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HidroforCurrentIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_HidroforCurrentIcon,200);

ui_FridgeCurrent = lv_obj_create(ui_RollerPanelCurrents);
lv_obj_set_width( ui_FridgeCurrent, 148);
lv_obj_set_height( ui_FridgeCurrent, 55);
lv_obj_set_x( ui_FridgeCurrent, -80 );
lv_obj_set_y( ui_FridgeCurrent, -11 );
lv_obj_set_align( ui_FridgeCurrent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FridgeCurrent, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_FridgeCurrent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FridgeCurrent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FridgeCurrent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeCurrentLabel = lv_label_create(ui_FridgeCurrent);
lv_obj_set_width( ui_FridgeCurrentLabel, 90);
lv_obj_set_height( ui_FridgeCurrentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeCurrentLabel, 24 );
lv_obj_set_y( ui_FridgeCurrentLabel, -14 );
lv_obj_set_align( ui_FridgeCurrentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FridgeCurrentLabel,"Fridge");
lv_obj_clear_flag( ui_FridgeCurrentLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_FridgeCurrentLabel, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeCurrentValue = lv_label_create(ui_FridgeCurrent);
lv_obj_set_width( ui_FridgeCurrentValue, 90);
lv_obj_set_height( ui_FridgeCurrentValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeCurrentValue, 24 );
lv_obj_set_y( ui_FridgeCurrentValue, 11 );
lv_obj_set_align( ui_FridgeCurrentValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_FridgeCurrentValue,"0.8 A");
lv_obj_clear_flag( ui_FridgeCurrentValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_FridgeCurrentValue, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeCurrentIcon = lv_img_create(ui_FridgeCurrent);
lv_img_set_src(ui_FridgeCurrentIcon, &ui_img_fridge_48_w_png);
lv_obj_set_width( ui_FridgeCurrentIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FridgeCurrentIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeCurrentIcon, -47 );
lv_obj_set_y( ui_FridgeCurrentIcon, 0 );
lv_obj_set_align( ui_FridgeCurrentIcon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FridgeCurrentIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_FridgeCurrentIcon,200);

ui_BatteryMonitor = lv_obj_create(ui_RollerPanelCurrents);
lv_obj_set_width( ui_BatteryMonitor, 296);
lv_obj_set_height( ui_BatteryMonitor, 62);
lv_obj_set_x( ui_BatteryMonitor, -6 );
lv_obj_set_y( ui_BatteryMonitor, 48 );
lv_obj_set_align( ui_BatteryMonitor, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BatteryMonitor, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_BatteryMonitor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BatteryMonitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatteryMonitor, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryMonitorLabel = lv_label_create(ui_BatteryMonitor);
lv_obj_set_width( ui_BatteryMonitorLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryMonitorLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryMonitorLabel, 9 );
lv_obj_set_y( ui_BatteryMonitorLabel, -11 );
lv_obj_set_align( ui_BatteryMonitorLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryMonitorLabel,"Battery");
lv_obj_clear_flag( ui_BatteryMonitorLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_BatteryMonitorLabel, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryMonitorVoltage = lv_label_create(ui_BatteryMonitor);
lv_obj_set_width( ui_BatteryMonitorVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryMonitorVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryMonitorVoltage, -2 );
lv_obj_set_y( ui_BatteryMonitorVoltage, 11 );
lv_obj_set_align( ui_BatteryMonitorVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryMonitorVoltage,"13.2 V");
lv_obj_clear_flag( ui_BatteryMonitorVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_BatteryMonitorVoltage, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryMonitorCurrent = lv_label_create(ui_BatteryMonitor);
lv_obj_set_width( ui_BatteryMonitorCurrent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryMonitorCurrent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryMonitorCurrent, 72 );
lv_obj_set_y( ui_BatteryMonitorCurrent, 11 );
lv_obj_set_align( ui_BatteryMonitorCurrent, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryMonitorCurrent,"10.8 A");
lv_obj_clear_flag( ui_BatteryMonitorCurrent, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_BatteryMonitorCurrent, &ui_font_Leddisplay16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryMonitorIcon = lv_img_create(ui_BatteryMonitor);
lv_img_set_src(ui_BatteryMonitorIcon, &ui_img_battery_84_w_png);
lv_obj_set_width( ui_BatteryMonitorIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryMonitorIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryMonitorIcon, -88 );
lv_obj_set_y( ui_BatteryMonitorIcon, 0 );
lv_obj_set_align( ui_BatteryMonitorIcon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BatteryMonitorIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_BatteryMonitorIcon,200);

ui_HeadContainer5 = lv_obj_create(ui_CurrentsMonitorScreen);
lv_obj_set_width( ui_HeadContainer5, 320);
lv_obj_set_height( ui_HeadContainer5, 28);
lv_obj_set_x( ui_HeadContainer5, 2 );
lv_obj_set_y( ui_HeadContainer5, -103 );
lv_obj_set_align( ui_HeadContainer5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HeadContainer5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadContainer5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadContainer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadContainer5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadContainer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OctoopiLogoImage5 = lv_img_create(ui_HeadContainer5);
lv_img_set_src(ui_OctoopiLogoImage5, &ui_img_octoopilogo_png);
lv_obj_set_width( ui_OctoopiLogoImage5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OctoopiLogoImage5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OctoopiLogoImage5, -147 );
lv_obj_set_y( ui_OctoopiLogoImage5, -1 );
lv_obj_set_align( ui_OctoopiLogoImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OctoopiLogoImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OctoopiLogoImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OctoopiLogoImage5,230);

ui_SetupImage5 = lv_img_create(ui_HeadContainer5);
lv_img_set_src(ui_SetupImage5, &ui_img_setup_png);
lv_obj_set_width( ui_SetupImage5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetupImage5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupImage5, 146 );
lv_obj_set_y( ui_SetupImage5, -1 );
lv_obj_set_align( ui_SetupImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetupImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SetupImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InMonitorContainer5 = lv_obj_create(ui_HeadContainer5);
lv_obj_set_width( ui_InMonitorContainer5, 212);
lv_obj_set_height( ui_InMonitorContainer5, 28);
lv_obj_set_x( ui_InMonitorContainer5, 5 );
lv_obj_set_y( ui_InMonitorContainer5, 0 );
lv_obj_set_align( ui_InMonitorContainer5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InMonitorContainer5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InMonitorContainer5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InMonitorContainer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InMonitorContainer5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InMonitorContainer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MonTrunkImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonTrunkImage5, &ui_img_trunk_open_png);
lv_obj_set_width( ui_MonTrunkImage5, 24);
lv_obj_set_height( ui_MonTrunkImage5, 24);
lv_obj_set_x( ui_MonTrunkImage5, -87 );
lv_obj_set_y( ui_MonTrunkImage5, -1 );
lv_obj_set_align( ui_MonTrunkImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonTrunkImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonTrunkImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonDoorImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonDoorImage5, &ui_img_door_lock_close_png);
lv_obj_set_width( ui_MonDoorImage5, 24);
lv_obj_set_height( ui_MonDoorImage5, 24);
lv_obj_set_x( ui_MonDoorImage5, -52 );
lv_obj_set_y( ui_MonDoorImage5, -1 );
lv_obj_set_align( ui_MonDoorImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonDoorImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonDoorImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonPlugImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonPlugImage5, &ui_img_plug_yes_png);
lv_obj_set_width( ui_MonPlugImage5, 24);
lv_obj_set_height( ui_MonPlugImage5, 24);
lv_obj_set_x( ui_MonPlugImage5, -15 );
lv_obj_set_y( ui_MonPlugImage5, -1 );
lv_obj_set_align( ui_MonPlugImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonPlugImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonPlugImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonLampImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonLampImage5, &ui_img_outdoor_lamp_on_png);
lv_obj_set_width( ui_MonLampImage5, 24);
lv_obj_set_height( ui_MonLampImage5, 24);
lv_obj_set_x( ui_MonLampImage5, 19 );
lv_obj_set_y( ui_MonLampImage5, -1 );
lv_obj_set_align( ui_MonLampImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonLampImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonLampImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonBlueImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonBlueImage5, &ui_img_bluetooth_yes_png);
lv_obj_set_width( ui_MonBlueImage5, 24);
lv_obj_set_height( ui_MonBlueImage5, 24);
lv_obj_set_x( ui_MonBlueImage5, 55 );
lv_obj_set_y( ui_MonBlueImage5, -1 );
lv_obj_set_align( ui_MonBlueImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonBlueImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonBlueImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonWifiImage5 = lv_img_create(ui_InMonitorContainer5);
lv_img_set_src(ui_MonWifiImage5, &ui_img_wifi_yes_png);
lv_obj_set_width( ui_MonWifiImage5, 24);
lv_obj_set_height( ui_MonWifiImage5, 24);
lv_obj_set_x( ui_MonWifiImage5, 89 );
lv_obj_set_y( ui_MonWifiImage5, -1 );
lv_obj_set_align( ui_MonWifiImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonWifiImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonWifiImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_FridgeCurrent, ui_event_FridgeCurrent, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BatteryMonitor, ui_event_BatteryMonitor, LV_EVENT_ALL, NULL);

}
