// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: elecrow

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
} /*extern "C"*/
#endif
#include "lvgl.h"

void up_click(lv_event_t * e);
void down_click(lv_event_t * e);
void left_click(lv_event_t * e);
void right_click(lv_event_t * e);




#endif
