// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: elecrow


#include "esp_log.h"
#include "ui_events.h"


void up_click(lv_event_t * e)
{
	// Your code here
	 ESP_LOGI("BTN", "UP Click");
}

void down_click(lv_event_t * e)
{
	// Your code here
		 ESP_LOGI("BTN", "DOWN Click");
}

void left_click(lv_event_t * e)
{
	// Your code here
		 ESP_LOGI("BTN", "LEFT Click");
}

void right_click(lv_event_t * e)
{
	// Your code here
		 ESP_LOGI("BTN", "RIGHT Click");
}

