// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"

void ui_FuseMonitorScreen_screen_init(void)
{
ui_FuseMonitorScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_FuseMonitorScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuseMonitorScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuseMonitorScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMonRow1 = lv_obj_create(ui_FuseMonitorScreen);
lv_obj_set_width( ui_FuseMonRow1, 273);
lv_obj_set_height( ui_FuseMonRow1, 92);
lv_obj_set_x( ui_FuseMonRow1, 4 );
lv_obj_set_y( ui_FuseMonRow1, -33 );
lv_obj_set_align( ui_FuseMonRow1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMonRow1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuseMonRow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuseMonRow1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuseMonRow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuseMonRow1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon1 = lv_obj_create(ui_FuseMonRow1);
lv_obj_set_width( ui_FuseMon1, 43);
lv_obj_set_height( ui_FuseMon1, 67);
lv_obj_set_x( ui_FuseMon1, -108 );
lv_obj_set_y( ui_FuseMon1, -1 );
lv_obj_set_align( ui_FuseMon1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage1 = lv_img_create(ui_FuseMon1);
lv_img_set_src(ui_FuseMonImage1, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage1, 0 );
lv_obj_set_y( ui_FuseMonImage1, 11 );
lv_obj_set_align( ui_FuseMonImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel1 = lv_label_create(ui_FuseMon1);
lv_obj_set_width( ui_FuseMonLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel1, -1 );
lv_obj_set_y( ui_FuseMonLabel1, -19 );
lv_obj_set_align( ui_FuseMonLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel1,"1");
lv_obj_set_style_text_font(ui_FuseMonLabel1, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon2 = lv_obj_create(ui_FuseMonRow1);
lv_obj_set_width( ui_FuseMon2, 43);
lv_obj_set_height( ui_FuseMon2, 67);
lv_obj_set_x( ui_FuseMon2, -55 );
lv_obj_set_y( ui_FuseMon2, -1 );
lv_obj_set_align( ui_FuseMon2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage2 = lv_img_create(ui_FuseMon2);
lv_img_set_src(ui_FuseMonImage2, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage2, 0 );
lv_obj_set_y( ui_FuseMonImage2, 11 );
lv_obj_set_align( ui_FuseMonImage2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel2 = lv_label_create(ui_FuseMon2);
lv_obj_set_width( ui_FuseMonLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel2, -1 );
lv_obj_set_y( ui_FuseMonLabel2, -19 );
lv_obj_set_align( ui_FuseMonLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel2,"2");
lv_obj_set_style_text_font(ui_FuseMonLabel2, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon3 = lv_obj_create(ui_FuseMonRow1);
lv_obj_set_width( ui_FuseMon3, 43);
lv_obj_set_height( ui_FuseMon3, 67);
lv_obj_set_x( ui_FuseMon3, -3 );
lv_obj_set_y( ui_FuseMon3, 0 );
lv_obj_set_align( ui_FuseMon3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage3 = lv_img_create(ui_FuseMon3);
lv_img_set_src(ui_FuseMonImage3, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage3, 0 );
lv_obj_set_y( ui_FuseMonImage3, 11 );
lv_obj_set_align( ui_FuseMonImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel3 = lv_label_create(ui_FuseMon3);
lv_obj_set_width( ui_FuseMonLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel3, -1 );
lv_obj_set_y( ui_FuseMonLabel3, -19 );
lv_obj_set_align( ui_FuseMonLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel3,"3");
lv_obj_set_style_text_font(ui_FuseMonLabel3, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon4 = lv_obj_create(ui_FuseMonRow1);
lv_obj_set_width( ui_FuseMon4, 43);
lv_obj_set_height( ui_FuseMon4, 67);
lv_obj_set_x( ui_FuseMon4, 47 );
lv_obj_set_y( ui_FuseMon4, 0 );
lv_obj_set_align( ui_FuseMon4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage4 = lv_img_create(ui_FuseMon4);
lv_img_set_src(ui_FuseMonImage4, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage4, 0 );
lv_obj_set_y( ui_FuseMonImage4, 11 );
lv_obj_set_align( ui_FuseMonImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel4 = lv_label_create(ui_FuseMon4);
lv_obj_set_width( ui_FuseMonLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel4, -1 );
lv_obj_set_y( ui_FuseMonLabel4, -19 );
lv_obj_set_align( ui_FuseMonLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel4,"4");
lv_obj_set_style_text_font(ui_FuseMonLabel4, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon5 = lv_obj_create(ui_FuseMonRow1);
lv_obj_set_width( ui_FuseMon5, 43);
lv_obj_set_height( ui_FuseMon5, 67);
lv_obj_set_x( ui_FuseMon5, 99 );
lv_obj_set_y( ui_FuseMon5, 0 );
lv_obj_set_align( ui_FuseMon5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage5 = lv_img_create(ui_FuseMon5);
lv_img_set_src(ui_FuseMonImage5, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage5, 0 );
lv_obj_set_y( ui_FuseMonImage5, 11 );
lv_obj_set_align( ui_FuseMonImage5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel5 = lv_label_create(ui_FuseMon5);
lv_obj_set_width( ui_FuseMonLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel5, -1 );
lv_obj_set_y( ui_FuseMonLabel5, -19 );
lv_obj_set_align( ui_FuseMonLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel5,"5");
lv_obj_set_style_text_font(ui_FuseMonLabel5, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMonRow2 = lv_obj_create(ui_FuseMonitorScreen);
lv_obj_set_width( ui_FuseMonRow2, 273);
lv_obj_set_height( ui_FuseMonRow2, 92);
lv_obj_set_x( ui_FuseMonRow2, 5 );
lv_obj_set_y( ui_FuseMonRow2, 52 );
lv_obj_set_align( ui_FuseMonRow2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMonRow2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FuseMonRow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FuseMonRow2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FuseMonRow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FuseMonRow2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon6 = lv_obj_create(ui_FuseMonRow2);
lv_obj_set_width( ui_FuseMon6, 43);
lv_obj_set_height( ui_FuseMon6, 67);
lv_obj_set_x( ui_FuseMon6, -108 );
lv_obj_set_y( ui_FuseMon6, -1 );
lv_obj_set_align( ui_FuseMon6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage6 = lv_img_create(ui_FuseMon6);
lv_img_set_src(ui_FuseMonImage6, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage6, 0 );
lv_obj_set_y( ui_FuseMonImage6, 11 );
lv_obj_set_align( ui_FuseMonImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel6 = lv_label_create(ui_FuseMon6);
lv_obj_set_width( ui_FuseMonLabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel6, -1 );
lv_obj_set_y( ui_FuseMonLabel6, -19 );
lv_obj_set_align( ui_FuseMonLabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel6,"6");
lv_obj_set_style_text_font(ui_FuseMonLabel6, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon7 = lv_obj_create(ui_FuseMonRow2);
lv_obj_set_width( ui_FuseMon7, 43);
lv_obj_set_height( ui_FuseMon7, 67);
lv_obj_set_x( ui_FuseMon7, -55 );
lv_obj_set_y( ui_FuseMon7, -1 );
lv_obj_set_align( ui_FuseMon7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage7 = lv_img_create(ui_FuseMon7);
lv_img_set_src(ui_FuseMonImage7, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage7, 0 );
lv_obj_set_y( ui_FuseMonImage7, 11 );
lv_obj_set_align( ui_FuseMonImage7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel7 = lv_label_create(ui_FuseMon7);
lv_obj_set_width( ui_FuseMonLabel7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel7, -1 );
lv_obj_set_y( ui_FuseMonLabel7, -19 );
lv_obj_set_align( ui_FuseMonLabel7, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel7,"7");
lv_obj_set_style_text_font(ui_FuseMonLabel7, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon8 = lv_obj_create(ui_FuseMonRow2);
lv_obj_set_width( ui_FuseMon8, 43);
lv_obj_set_height( ui_FuseMon8, 67);
lv_obj_set_x( ui_FuseMon8, -3 );
lv_obj_set_y( ui_FuseMon8, 0 );
lv_obj_set_align( ui_FuseMon8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage8 = lv_img_create(ui_FuseMon8);
lv_img_set_src(ui_FuseMonImage8, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage8, 0 );
lv_obj_set_y( ui_FuseMonImage8, 11 );
lv_obj_set_align( ui_FuseMonImage8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_FuseMonImage8, lv_color_hex(0xDD0000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_FuseMonImage8, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMonLabel8 = lv_label_create(ui_FuseMon8);
lv_obj_set_width( ui_FuseMonLabel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel8, -1 );
lv_obj_set_y( ui_FuseMonLabel8, -19 );
lv_obj_set_align( ui_FuseMonLabel8, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel8,"8");
lv_obj_set_style_text_font(ui_FuseMonLabel8, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon9 = lv_obj_create(ui_FuseMonRow2);
lv_obj_set_width( ui_FuseMon9, 43);
lv_obj_set_height( ui_FuseMon9, 67);
lv_obj_set_x( ui_FuseMon9, 47 );
lv_obj_set_y( ui_FuseMon9, 0 );
lv_obj_set_align( ui_FuseMon9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage9 = lv_img_create(ui_FuseMon9);
lv_img_set_src(ui_FuseMonImage9, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage9, 0 );
lv_obj_set_y( ui_FuseMonImage9, 11 );
lv_obj_set_align( ui_FuseMonImage9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel9 = lv_label_create(ui_FuseMon9);
lv_obj_set_width( ui_FuseMonLabel9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel9, -1 );
lv_obj_set_y( ui_FuseMonLabel9, -19 );
lv_obj_set_align( ui_FuseMonLabel9, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel9,"9");
lv_obj_set_style_text_font(ui_FuseMonLabel9, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FuseMon10 = lv_obj_create(ui_FuseMonRow2);
lv_obj_set_width( ui_FuseMon10, 43);
lv_obj_set_height( ui_FuseMon10, 67);
lv_obj_set_x( ui_FuseMon10, 99 );
lv_obj_set_y( ui_FuseMon10, 0 );
lv_obj_set_align( ui_FuseMon10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FuseMon10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonImage10 = lv_img_create(ui_FuseMon10);
lv_img_set_src(ui_FuseMonImage10, &ui_img_fuse_w_png);
lv_obj_set_width( ui_FuseMonImage10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonImage10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonImage10, 0 );
lv_obj_set_y( ui_FuseMonImage10, 11 );
lv_obj_set_align( ui_FuseMonImage10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FuseMonImage10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FuseMonImage10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FuseMonLabel10 = lv_label_create(ui_FuseMon10);
lv_obj_set_width( ui_FuseMonLabel10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FuseMonLabel10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FuseMonLabel10, -1 );
lv_obj_set_y( ui_FuseMonLabel10, -19 );
lv_obj_set_align( ui_FuseMonLabel10, LV_ALIGN_CENTER );
lv_label_set_text(ui_FuseMonLabel10,"10");
lv_obj_set_style_text_font(ui_FuseMonLabel10, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadContainer3 = lv_obj_create(ui_FuseMonitorScreen);
lv_obj_set_width( ui_HeadContainer3, 320);
lv_obj_set_height( ui_HeadContainer3, 28);
lv_obj_set_x( ui_HeadContainer3, 1 );
lv_obj_set_y( ui_HeadContainer3, -103 );
lv_obj_set_align( ui_HeadContainer3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HeadContainer3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadContainer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadContainer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OctoopiLogoImage3 = lv_img_create(ui_HeadContainer3);
lv_img_set_src(ui_OctoopiLogoImage3, &ui_img_octoopilogo_png);
lv_obj_set_width( ui_OctoopiLogoImage3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OctoopiLogoImage3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OctoopiLogoImage3, -147 );
lv_obj_set_y( ui_OctoopiLogoImage3, -1 );
lv_obj_set_align( ui_OctoopiLogoImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OctoopiLogoImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OctoopiLogoImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OctoopiLogoImage3,230);

ui_SetupImage3 = lv_img_create(ui_HeadContainer3);
lv_img_set_src(ui_SetupImage3, &ui_img_setup_png);
lv_obj_set_width( ui_SetupImage3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetupImage3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupImage3, 146 );
lv_obj_set_y( ui_SetupImage3, -1 );
lv_obj_set_align( ui_SetupImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetupImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SetupImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InMonitorContainer3 = lv_obj_create(ui_HeadContainer3);
lv_obj_set_width( ui_InMonitorContainer3, 212);
lv_obj_set_height( ui_InMonitorContainer3, 28);
lv_obj_set_x( ui_InMonitorContainer3, 5 );
lv_obj_set_y( ui_InMonitorContainer3, 0 );
lv_obj_set_align( ui_InMonitorContainer3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InMonitorContainer3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InMonitorContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InMonitorContainer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InMonitorContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InMonitorContainer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MonTrunkImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonTrunkImage3, &ui_img_trunk_open_png);
lv_obj_set_width( ui_MonTrunkImage3, 24);
lv_obj_set_height( ui_MonTrunkImage3, 24);
lv_obj_set_x( ui_MonTrunkImage3, -87 );
lv_obj_set_y( ui_MonTrunkImage3, -1 );
lv_obj_set_align( ui_MonTrunkImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonTrunkImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonTrunkImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonDoorImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonDoorImage3, &ui_img_door_lock_close_png);
lv_obj_set_width( ui_MonDoorImage3, 24);
lv_obj_set_height( ui_MonDoorImage3, 24);
lv_obj_set_x( ui_MonDoorImage3, -52 );
lv_obj_set_y( ui_MonDoorImage3, -1 );
lv_obj_set_align( ui_MonDoorImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonDoorImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonDoorImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonPlugImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonPlugImage3, &ui_img_plug_yes_png);
lv_obj_set_width( ui_MonPlugImage3, 24);
lv_obj_set_height( ui_MonPlugImage3, 24);
lv_obj_set_x( ui_MonPlugImage3, -15 );
lv_obj_set_y( ui_MonPlugImage3, -1 );
lv_obj_set_align( ui_MonPlugImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonPlugImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonPlugImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonLampImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonLampImage3, &ui_img_outdoor_lamp_on_png);
lv_obj_set_width( ui_MonLampImage3, 24);
lv_obj_set_height( ui_MonLampImage3, 24);
lv_obj_set_x( ui_MonLampImage3, 19 );
lv_obj_set_y( ui_MonLampImage3, -1 );
lv_obj_set_align( ui_MonLampImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonLampImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonLampImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonBlueImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonBlueImage3, &ui_img_bluetooth_yes_png);
lv_obj_set_width( ui_MonBlueImage3, 24);
lv_obj_set_height( ui_MonBlueImage3, 24);
lv_obj_set_x( ui_MonBlueImage3, 55 );
lv_obj_set_y( ui_MonBlueImage3, -1 );
lv_obj_set_align( ui_MonBlueImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonBlueImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonBlueImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonWifiImage3 = lv_img_create(ui_InMonitorContainer3);
lv_img_set_src(ui_MonWifiImage3, &ui_img_wifi_yes_png);
lv_obj_set_width( ui_MonWifiImage3, 24);
lv_obj_set_height( ui_MonWifiImage3, 24);
lv_obj_set_x( ui_MonWifiImage3, 89 );
lv_obj_set_y( ui_MonWifiImage3, -1 );
lv_obj_set_align( ui_MonWifiImage3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonWifiImage3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonWifiImage3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
