// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"

void ui_LampControlScreen_screen_init(void)
{
ui_LampControlScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LampControlScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LampControlScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LampControlScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IndoorLampOnOffImage = lv_img_create(ui_LampControlScreen);
lv_img_set_src(ui_IndoorLampOnOffImage, &ui_img_1521626150);
lv_obj_set_width( ui_IndoorLampOnOffImage, 100);
lv_obj_set_height( ui_IndoorLampOnOffImage, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_IndoorLampOnOffImage, -49 );
lv_obj_set_y( ui_IndoorLampOnOffImage, -17 );
lv_obj_set_align( ui_IndoorLampOnOffImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_IndoorLampOnOffImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IndoorLampOnOffImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_IndoorLampOnOffIcon = lv_img_create(ui_IndoorLampOnOffImage);
lv_img_set_src(ui_IndoorLampOnOffIcon, &ui_img_indoor_lamp_48_w_png);
lv_obj_set_width( ui_IndoorLampOnOffIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IndoorLampOnOffIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IndoorLampOnOffIcon, 2 );
lv_obj_set_y( ui_IndoorLampOnOffIcon, -1 );
lv_obj_set_align( ui_IndoorLampOnOffIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_IndoorLampOnOffIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IndoorLampOnOffIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OutdoorLampOnOffImage = lv_img_create(ui_LampControlScreen);
lv_img_set_src(ui_OutdoorLampOnOffImage, &ui_img_input_card_png);
lv_obj_set_width( ui_OutdoorLampOnOffImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutdoorLampOnOffImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutdoorLampOnOffImage, 64 );
lv_obj_set_y( ui_OutdoorLampOnOffImage, -18 );
lv_obj_set_align( ui_OutdoorLampOnOffImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OutdoorLampOnOffImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OutdoorLampOnOffImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OutdoorLampOnOffIcon = lv_img_create(ui_OutdoorLampOnOffImage);
lv_img_set_src(ui_OutdoorLampOnOffIcon, &ui_img_outdoor_lamp_48_w_png);
lv_obj_set_width( ui_OutdoorLampOnOffIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OutdoorLampOnOffIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OutdoorLampOnOffIcon, 4 );
lv_obj_set_y( ui_OutdoorLampOnOffIcon, -3 );
lv_obj_set_align( ui_OutdoorLampOnOffIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OutdoorLampOnOffIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OutdoorLampOnOffIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DimmerLampPanel = lv_obj_create(ui_LampControlScreen);
lv_obj_set_width( ui_DimmerLampPanel, 265);
lv_obj_set_height( ui_DimmerLampPanel, 59);
lv_obj_set_x( ui_DimmerLampPanel, -2 );
lv_obj_set_y( ui_DimmerLampPanel, 74 );
lv_obj_set_align( ui_DimmerLampPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DimmerLampPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider2 = lv_slider_create(ui_DimmerLampPanel);
lv_obj_set_width( ui_Slider2, 150);
lv_obj_set_height( ui_Slider2, 10);
lv_obj_set_x( ui_Slider2, 5 );
lv_obj_set_y( ui_Slider2, 0 );
lv_obj_set_align( ui_Slider2, LV_ALIGN_CENTER );


ui_DimmerLampPercentLabel = lv_label_create(ui_DimmerLampPanel);
lv_obj_set_width( ui_DimmerLampPercentLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DimmerLampPercentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DimmerLampPercentLabel, 103 );
lv_obj_set_y( ui_DimmerLampPercentLabel, 2 );
lv_obj_set_align( ui_DimmerLampPercentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DimmerLampPercentLabel,"%15");

ui_DimmerLampIcon = lv_img_create(ui_DimmerLampPanel);
lv_img_set_src(ui_DimmerLampIcon, &ui_img_indoor_lamp_48_g_png);
lv_obj_set_width( ui_DimmerLampIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DimmerLampIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DimmerLampIcon, -103 );
lv_obj_set_y( ui_DimmerLampIcon, 1 );
lv_obj_set_align( ui_DimmerLampIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DimmerLampIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DimmerLampIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HeadContainer1 = lv_obj_create(ui_LampControlScreen);
lv_obj_set_width( ui_HeadContainer1, 320);
lv_obj_set_height( ui_HeadContainer1, 28);
lv_obj_set_x( ui_HeadContainer1, 1 );
lv_obj_set_y( ui_HeadContainer1, -103 );
lv_obj_set_align( ui_HeadContainer1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HeadContainer1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadContainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadContainer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadContainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadContainer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OctoopiLogoImage1 = lv_img_create(ui_HeadContainer1);
lv_img_set_src(ui_OctoopiLogoImage1, &ui_img_octoopilogo_png);
lv_obj_set_width( ui_OctoopiLogoImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OctoopiLogoImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OctoopiLogoImage1, -147 );
lv_obj_set_y( ui_OctoopiLogoImage1, -1 );
lv_obj_set_align( ui_OctoopiLogoImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OctoopiLogoImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OctoopiLogoImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OctoopiLogoImage1,230);

ui_SetupImage1 = lv_img_create(ui_HeadContainer1);
lv_img_set_src(ui_SetupImage1, &ui_img_setup_png);
lv_obj_set_width( ui_SetupImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetupImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupImage1, 146 );
lv_obj_set_y( ui_SetupImage1, -1 );
lv_obj_set_align( ui_SetupImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetupImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SetupImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InMonitorContainer1 = lv_obj_create(ui_HeadContainer1);
lv_obj_set_width( ui_InMonitorContainer1, 212);
lv_obj_set_height( ui_InMonitorContainer1, 28);
lv_obj_set_x( ui_InMonitorContainer1, 5 );
lv_obj_set_y( ui_InMonitorContainer1, 0 );
lv_obj_set_align( ui_InMonitorContainer1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InMonitorContainer1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InMonitorContainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InMonitorContainer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InMonitorContainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InMonitorContainer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MonTrunkImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonTrunkImage1, &ui_img_trunk_open_png);
lv_obj_set_width( ui_MonTrunkImage1, 24);
lv_obj_set_height( ui_MonTrunkImage1, 24);
lv_obj_set_x( ui_MonTrunkImage1, -87 );
lv_obj_set_y( ui_MonTrunkImage1, -1 );
lv_obj_set_align( ui_MonTrunkImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonTrunkImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonTrunkImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonDoorImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonDoorImage1, &ui_img_door_lock_close_png);
lv_obj_set_width( ui_MonDoorImage1, 24);
lv_obj_set_height( ui_MonDoorImage1, 24);
lv_obj_set_x( ui_MonDoorImage1, -52 );
lv_obj_set_y( ui_MonDoorImage1, -1 );
lv_obj_set_align( ui_MonDoorImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonDoorImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonDoorImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonPlugImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonPlugImage1, &ui_img_plug_yes_png);
lv_obj_set_width( ui_MonPlugImage1, 24);
lv_obj_set_height( ui_MonPlugImage1, 24);
lv_obj_set_x( ui_MonPlugImage1, -15 );
lv_obj_set_y( ui_MonPlugImage1, -1 );
lv_obj_set_align( ui_MonPlugImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonPlugImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonPlugImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonLampImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonLampImage1, &ui_img_outdoor_lamp_on_png);
lv_obj_set_width( ui_MonLampImage1, 24);
lv_obj_set_height( ui_MonLampImage1, 24);
lv_obj_set_x( ui_MonLampImage1, 19 );
lv_obj_set_y( ui_MonLampImage1, -1 );
lv_obj_set_align( ui_MonLampImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonLampImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonLampImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonBlueImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonBlueImage1, &ui_img_bluetooth_yes_png);
lv_obj_set_width( ui_MonBlueImage1, 24);
lv_obj_set_height( ui_MonBlueImage1, 24);
lv_obj_set_x( ui_MonBlueImage1, 55 );
lv_obj_set_y( ui_MonBlueImage1, -1 );
lv_obj_set_align( ui_MonBlueImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonBlueImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonBlueImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonWifiImage1 = lv_img_create(ui_InMonitorContainer1);
lv_img_set_src(ui_MonWifiImage1, &ui_img_wifi_yes_png);
lv_obj_set_width( ui_MonWifiImage1, 24);
lv_obj_set_height( ui_MonWifiImage1, 24);
lv_obj_set_x( ui_MonWifiImage1, 89 );
lv_obj_set_y( ui_MonWifiImage1, -1 );
lv_obj_set_align( ui_MonWifiImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonWifiImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonWifiImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
