// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"

void ui_PopupScreen_screen_init(void)
{
ui_PopupScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PopupScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PopupScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PopupScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadContainer6 = lv_obj_create(ui_PopupScreen);
lv_obj_set_width( ui_HeadContainer6, 320);
lv_obj_set_height( ui_HeadContainer6, 28);
lv_obj_set_x( ui_HeadContainer6, 1 );
lv_obj_set_y( ui_HeadContainer6, -103 );
lv_obj_set_align( ui_HeadContainer6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HeadContainer6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadContainer6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadContainer6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OctoopiLogoImage6 = lv_img_create(ui_HeadContainer6);
lv_img_set_src(ui_OctoopiLogoImage6, &ui_img_octoopilogo_png);
lv_obj_set_width( ui_OctoopiLogoImage6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OctoopiLogoImage6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OctoopiLogoImage6, -147 );
lv_obj_set_y( ui_OctoopiLogoImage6, -1 );
lv_obj_set_align( ui_OctoopiLogoImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OctoopiLogoImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OctoopiLogoImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OctoopiLogoImage6,230);

ui_SetupImage6 = lv_img_create(ui_HeadContainer6);
lv_img_set_src(ui_SetupImage6, &ui_img_setup_png);
lv_obj_set_width( ui_SetupImage6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetupImage6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupImage6, 146 );
lv_obj_set_y( ui_SetupImage6, -1 );
lv_obj_set_align( ui_SetupImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetupImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SetupImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InMonitorContainer6 = lv_obj_create(ui_HeadContainer6);
lv_obj_set_width( ui_InMonitorContainer6, 212);
lv_obj_set_height( ui_InMonitorContainer6, 28);
lv_obj_set_x( ui_InMonitorContainer6, 5 );
lv_obj_set_y( ui_InMonitorContainer6, 0 );
lv_obj_set_align( ui_InMonitorContainer6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InMonitorContainer6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InMonitorContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InMonitorContainer6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InMonitorContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InMonitorContainer6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MonTrunkImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonTrunkImage6, &ui_img_trunk_open_png);
lv_obj_set_width( ui_MonTrunkImage6, 24);
lv_obj_set_height( ui_MonTrunkImage6, 24);
lv_obj_set_x( ui_MonTrunkImage6, -87 );
lv_obj_set_y( ui_MonTrunkImage6, -1 );
lv_obj_set_align( ui_MonTrunkImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonTrunkImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonTrunkImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonDoorImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonDoorImage6, &ui_img_door_lock_close_png);
lv_obj_set_width( ui_MonDoorImage6, 24);
lv_obj_set_height( ui_MonDoorImage6, 24);
lv_obj_set_x( ui_MonDoorImage6, -52 );
lv_obj_set_y( ui_MonDoorImage6, -1 );
lv_obj_set_align( ui_MonDoorImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonDoorImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonDoorImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonPlugImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonPlugImage6, &ui_img_plug_yes_png);
lv_obj_set_width( ui_MonPlugImage6, 24);
lv_obj_set_height( ui_MonPlugImage6, 24);
lv_obj_set_x( ui_MonPlugImage6, -15 );
lv_obj_set_y( ui_MonPlugImage6, -1 );
lv_obj_set_align( ui_MonPlugImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonPlugImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonPlugImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonLampImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonLampImage6, &ui_img_outdoor_lamp_on_png);
lv_obj_set_width( ui_MonLampImage6, 24);
lv_obj_set_height( ui_MonLampImage6, 24);
lv_obj_set_x( ui_MonLampImage6, 19 );
lv_obj_set_y( ui_MonLampImage6, -1 );
lv_obj_set_align( ui_MonLampImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonLampImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonLampImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonBlueImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonBlueImage6, &ui_img_bluetooth_yes_png);
lv_obj_set_width( ui_MonBlueImage6, 24);
lv_obj_set_height( ui_MonBlueImage6, 24);
lv_obj_set_x( ui_MonBlueImage6, 55 );
lv_obj_set_y( ui_MonBlueImage6, -1 );
lv_obj_set_align( ui_MonBlueImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonBlueImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonBlueImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonWifiImage6 = lv_img_create(ui_InMonitorContainer6);
lv_img_set_src(ui_MonWifiImage6, &ui_img_wifi_yes_png);
lv_obj_set_width( ui_MonWifiImage6, 24);
lv_obj_set_height( ui_MonWifiImage6, 24);
lv_obj_set_x( ui_MonWifiImage6, 89 );
lv_obj_set_y( ui_MonWifiImage6, -1 );
lv_obj_set_align( ui_MonWifiImage6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonWifiImage6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonWifiImage6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PopupContainer = lv_obj_create(ui_PopupScreen);
lv_obj_set_width( ui_PopupContainer, 252);
lv_obj_set_height( ui_PopupContainer, 173);
lv_obj_set_x( ui_PopupContainer, 3 );
lv_obj_set_y( ui_PopupContainer, 11 );
lv_obj_set_align( ui_PopupContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PopupContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PopupContainer, lv_color_hex(0xF40A0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PopupContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PopupImage = lv_img_create(ui_PopupContainer);
lv_img_set_src(ui_PopupImage, &ui_img_fridge_48_w_png);
lv_obj_set_width( ui_PopupImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PopupImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PopupImage, -7 );
lv_obj_set_y( ui_PopupImage, -42 );
lv_obj_set_align( ui_PopupImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PopupImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PopupImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PopupLabel = lv_label_create(ui_PopupScreen);
lv_obj_set_width( ui_PopupLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PopupLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PopupLabel, 3 );
lv_obj_set_y( ui_PopupLabel, 28 );
lv_obj_set_align( ui_PopupLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PopupLabel,"Buzdolabi cikis hatasi !\nLutfen kontrol ediniz");

ui_PopupButton = lv_btn_create(ui_PopupScreen);
lv_obj_set_width( ui_PopupButton, 100);
lv_obj_set_height( ui_PopupButton, 36);
lv_obj_set_x( ui_PopupButton, 1 );
lv_obj_set_y( ui_PopupButton, 75 );
lv_obj_set_align( ui_PopupButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PopupButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PopupButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PopupButtonLabel = lv_label_create(ui_PopupButton);
lv_obj_set_width( ui_PopupButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PopupButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PopupButtonLabel, -2 );
lv_obj_set_y( ui_PopupButtonLabel, 1 );
lv_obj_set_align( ui_PopupButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PopupButtonLabel,"Tamam");
lv_obj_set_style_text_color(ui_PopupButtonLabel, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PopupButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PopupButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

}
