// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: MiniCombine2

#include "ui.h"

void ui_RGBLampScreen_screen_init(void)
{
ui_RGBLampScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_RGBLampScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RGBLampScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RGBLampScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetContainer = lv_obj_create(ui_RGBLampScreen);
lv_obj_set_width( ui_RGBSetContainer, 154);
lv_obj_set_height( ui_RGBSetContainer, 188);
lv_obj_set_x( ui_RGBSetContainer, -76 );
lv_obj_set_y( ui_RGBSetContainer, 14 );
lv_obj_set_align( ui_RGBSetContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RGBSetContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RGBSetContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RGBSetContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetColorwheel = lv_colorwheel_create(ui_RGBSetContainer,true);
lv_obj_set_width( ui_RGBSetColorwheel, 100);
lv_obj_set_height( ui_RGBSetColorwheel, 100);
lv_obj_set_x( ui_RGBSetColorwheel, 0 );
lv_obj_set_y( ui_RGBSetColorwheel, -23 );
lv_obj_set_align( ui_RGBSetColorwheel, LV_ALIGN_CENTER );

ui_RGBSetSwitch = lv_switch_create(ui_RGBSetContainer);
lv_obj_set_width( ui_RGBSetSwitch, 50);
lv_obj_set_height( ui_RGBSetSwitch, 25);
lv_obj_set_x( ui_RGBSetSwitch, -2 );
lv_obj_set_y( ui_RGBSetSwitch, 75 );
lv_obj_set_align( ui_RGBSetSwitch, LV_ALIGN_CENTER );


ui_RGBFunctionContainer = lv_obj_create(ui_RGBLampScreen);
lv_obj_set_width( ui_RGBFunctionContainer, 145);
lv_obj_set_height( ui_RGBFunctionContainer, 188);
lv_obj_set_x( ui_RGBFunctionContainer, 81 );
lv_obj_set_y( ui_RGBFunctionContainer, 15 );
lv_obj_set_align( ui_RGBFunctionContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RGBFunctionContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RGBFunctionContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RGBFunctionContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF1Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF1Button, 55);
lv_obj_set_height( ui_RGBSetF1Button, 48);
lv_obj_set_x( ui_RGBSetF1Button, -34 );
lv_obj_set_y( ui_RGBSetF1Button, -59 );
lv_obj_set_align( ui_RGBSetF1Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF1Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF1Label = lv_label_create(ui_RGBSetF1Button);
lv_obj_set_width( ui_RGBSetF1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF1Label,"F1");
lv_obj_set_style_text_font(ui_RGBSetF1Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF2Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF2Button, 55);
lv_obj_set_height( ui_RGBSetF2Button, 48);
lv_obj_set_x( ui_RGBSetF2Button, 37 );
lv_obj_set_y( ui_RGBSetF2Button, -59 );
lv_obj_set_align( ui_RGBSetF2Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF2Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF2Label = lv_label_create(ui_RGBSetF2Button);
lv_obj_set_width( ui_RGBSetF2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF2Label,"F2");
lv_obj_set_style_text_font(ui_RGBSetF2Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF3Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF3Button, 55);
lv_obj_set_height( ui_RGBSetF3Button, 48);
lv_obj_set_x( ui_RGBSetF3Button, -34 );
lv_obj_set_y( ui_RGBSetF3Button, 0 );
lv_obj_set_align( ui_RGBSetF3Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF3Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF3Label = lv_label_create(ui_RGBSetF3Button);
lv_obj_set_width( ui_RGBSetF3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF3Label,"F3");
lv_obj_set_style_text_font(ui_RGBSetF3Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF4Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF4Button, 55);
lv_obj_set_height( ui_RGBSetF4Button, 48);
lv_obj_set_x( ui_RGBSetF4Button, 38 );
lv_obj_set_y( ui_RGBSetF4Button, 0 );
lv_obj_set_align( ui_RGBSetF4Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF4Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF4Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF4Label = lv_label_create(ui_RGBSetF4Button);
lv_obj_set_width( ui_RGBSetF4Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF4Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF4Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF4Label,"F4");
lv_obj_set_style_text_font(ui_RGBSetF4Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF5Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF5Button, 55);
lv_obj_set_height( ui_RGBSetF5Button, 48);
lv_obj_set_x( ui_RGBSetF5Button, -34 );
lv_obj_set_y( ui_RGBSetF5Button, 59 );
lv_obj_set_align( ui_RGBSetF5Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF5Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF5Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF5Label = lv_label_create(ui_RGBSetF5Button);
lv_obj_set_width( ui_RGBSetF5Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF5Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF5Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF5Label,"F5");
lv_obj_set_style_text_font(ui_RGBSetF5Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RGBSetF6Button = lv_btn_create(ui_RGBFunctionContainer);
lv_obj_set_width( ui_RGBSetF6Button, 55);
lv_obj_set_height( ui_RGBSetF6Button, 48);
lv_obj_set_x( ui_RGBSetF6Button, 37 );
lv_obj_set_y( ui_RGBSetF6Button, 59 );
lv_obj_set_align( ui_RGBSetF6Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RGBSetF6Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RGBSetF6Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RGBSetF6Label = lv_label_create(ui_RGBSetF6Button);
lv_obj_set_width( ui_RGBSetF6Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RGBSetF6Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RGBSetF6Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_RGBSetF6Label,"F6");
lv_obj_set_style_text_font(ui_RGBSetF6Label, &ui_font_Leddisplay20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadContainer4 = lv_obj_create(ui_RGBLampScreen);
lv_obj_set_width( ui_HeadContainer4, 320);
lv_obj_set_height( ui_HeadContainer4, 28);
lv_obj_set_x( ui_HeadContainer4, 1 );
lv_obj_set_y( ui_HeadContainer4, -103 );
lv_obj_set_align( ui_HeadContainer4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HeadContainer4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeadContainer4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadContainer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadContainer4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadContainer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OctoopiLogoImage4 = lv_img_create(ui_HeadContainer4);
lv_img_set_src(ui_OctoopiLogoImage4, &ui_img_octoopilogo_png);
lv_obj_set_width( ui_OctoopiLogoImage4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OctoopiLogoImage4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OctoopiLogoImage4, -147 );
lv_obj_set_y( ui_OctoopiLogoImage4, -1 );
lv_obj_set_align( ui_OctoopiLogoImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OctoopiLogoImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OctoopiLogoImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OctoopiLogoImage4,230);

ui_SetupImage4 = lv_img_create(ui_HeadContainer4);
lv_img_set_src(ui_SetupImage4, &ui_img_setup_png);
lv_obj_set_width( ui_SetupImage4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetupImage4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupImage4, 146 );
lv_obj_set_y( ui_SetupImage4, -1 );
lv_obj_set_align( ui_SetupImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetupImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SetupImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InMonitorContainer4 = lv_obj_create(ui_HeadContainer4);
lv_obj_set_width( ui_InMonitorContainer4, 212);
lv_obj_set_height( ui_InMonitorContainer4, 28);
lv_obj_set_x( ui_InMonitorContainer4, 5 );
lv_obj_set_y( ui_InMonitorContainer4, 0 );
lv_obj_set_align( ui_InMonitorContainer4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InMonitorContainer4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InMonitorContainer4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InMonitorContainer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InMonitorContainer4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InMonitorContainer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MonTrunkImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonTrunkImage4, &ui_img_trunk_open_png);
lv_obj_set_width( ui_MonTrunkImage4, 24);
lv_obj_set_height( ui_MonTrunkImage4, 24);
lv_obj_set_x( ui_MonTrunkImage4, -87 );
lv_obj_set_y( ui_MonTrunkImage4, -1 );
lv_obj_set_align( ui_MonTrunkImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonTrunkImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonTrunkImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonDoorImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonDoorImage4, &ui_img_door_lock_close_png);
lv_obj_set_width( ui_MonDoorImage4, 24);
lv_obj_set_height( ui_MonDoorImage4, 24);
lv_obj_set_x( ui_MonDoorImage4, -52 );
lv_obj_set_y( ui_MonDoorImage4, -1 );
lv_obj_set_align( ui_MonDoorImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonDoorImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonDoorImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonPlugImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonPlugImage4, &ui_img_plug_yes_png);
lv_obj_set_width( ui_MonPlugImage4, 24);
lv_obj_set_height( ui_MonPlugImage4, 24);
lv_obj_set_x( ui_MonPlugImage4, -15 );
lv_obj_set_y( ui_MonPlugImage4, -1 );
lv_obj_set_align( ui_MonPlugImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonPlugImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonPlugImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonLampImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonLampImage4, &ui_img_outdoor_lamp_on_png);
lv_obj_set_width( ui_MonLampImage4, 24);
lv_obj_set_height( ui_MonLampImage4, 24);
lv_obj_set_x( ui_MonLampImage4, 19 );
lv_obj_set_y( ui_MonLampImage4, -1 );
lv_obj_set_align( ui_MonLampImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonLampImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonLampImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonBlueImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonBlueImage4, &ui_img_bluetooth_yes_png);
lv_obj_set_width( ui_MonBlueImage4, 24);
lv_obj_set_height( ui_MonBlueImage4, 24);
lv_obj_set_x( ui_MonBlueImage4, 55 );
lv_obj_set_y( ui_MonBlueImage4, -1 );
lv_obj_set_align( ui_MonBlueImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonBlueImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonBlueImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonWifiImage4 = lv_img_create(ui_InMonitorContainer4);
lv_img_set_src(ui_MonWifiImage4, &ui_img_wifi_yes_png);
lv_obj_set_width( ui_MonWifiImage4, 24);
lv_obj_set_height( ui_MonWifiImage4, 24);
lv_obj_set_x( ui_MonWifiImage4, 89 );
lv_obj_set_y( ui_MonWifiImage4, -1 );
lv_obj_set_align( ui_MonWifiImage4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MonWifiImage4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MonWifiImage4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
