// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: elecrow

#include "ui.h"

void ui_Screen_2_Move_screen_init(void)
{
ui_Screen_2_Move = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_2_Move, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_2_Move, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_2_Move, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Background1 = lv_img_create(ui_Screen_2_Move);
lv_img_set_src(ui_Background1, &ui_img_bg_png);
lv_obj_set_width( ui_Background1, 800);
lv_obj_set_height( ui_Background1, 480);
lv_obj_set_align( ui_Background1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Background1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_S1_Content_Panel1 = lv_obj_create(ui_Screen_2_Move);
lv_obj_set_width( ui_S1_Content_Panel1, 292);
lv_obj_set_height( ui_S1_Content_Panel1, 304);
lv_obj_set_x( ui_S1_Content_Panel1, -501 );
lv_obj_set_y( ui_S1_Content_Panel1, 3 );
lv_obj_set_align( ui_S1_Content_Panel1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_S1_Content_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_S1_Content_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_S1_Content_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Move_XY = lv_img_create(ui_S1_Content_Panel1);
lv_img_set_src(ui_BTN_Move_XY, &ui_img_btn_pad_bottom_png);
lv_obj_set_width( ui_BTN_Move_XY, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Move_XY, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Move_XY, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Move_XY, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_BTN_Move_XY_Top = lv_img_create(ui_BTN_Move_XY);
lv_img_set_src(ui_BTN_Move_XY_Top, &ui_img_btn_pad_top_png);
lv_obj_set_width( ui_BTN_Move_XY_Top, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Move_XY_Top, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Move_XY_Top, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Move_XY_Top, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_img_set_pivot(ui_BTN_Move_XY_Top,121,118);

ui_Arrow_Up_2 = lv_img_create(ui_BTN_Move_XY_Top);
lv_img_set_src(ui_Arrow_Up_2, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_Up_2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Up_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Up_2, 0 );
lv_obj_set_y( ui_Arrow_Up_2, 25 );
lv_obj_set_align( ui_Arrow_Up_2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Arrow_Up_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Up_2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Up_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Up_2, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Up_2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_Down_2 = lv_img_create(ui_BTN_Move_XY_Top);
lv_img_set_src(ui_Arrow_Down_2, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_Down_2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Down_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Down_2, 0 );
lv_obj_set_y( ui_Arrow_Down_2, -25 );
lv_obj_set_align( ui_Arrow_Down_2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Arrow_Down_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Down_2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Down_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Down_2, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Down_2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_Left_2 = lv_img_create(ui_BTN_Move_XY_Top);
lv_img_set_src(ui_Arrow_Left_2, &ui_img_arrow_left_png);
lv_obj_set_width( ui_Arrow_Left_2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Left_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Left_2, 25 );
lv_obj_set_y( ui_Arrow_Left_2, 0 );
lv_obj_set_align( ui_Arrow_Left_2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Arrow_Left_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Left_2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Left_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Left_2, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Left_2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_Right_2 = lv_img_create(ui_BTN_Move_XY_Top);
lv_img_set_src(ui_Arrow_Right_2, &ui_img_arrow_right_png);
lv_obj_set_width( ui_Arrow_Right_2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Right_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Right_2, -25 );
lv_obj_set_y( ui_Arrow_Right_2, 0 );
lv_obj_set_align( ui_Arrow_Right_2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Arrow_Right_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Right_2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Right_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Right_2, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Right_2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Image1 = lv_img_create(ui_Screen_2_Move);
lv_img_set_src(ui_Image1, &ui_img_e1_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 179 );
lv_obj_set_y( ui_Image1, -34 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
